INSERT INTO BRAND(CODE) VALUES
  ('ADIDAS'),
  ('PUMA'),
  ('NIKE');
  
INSERT INTO COLOR(CODE)  VALUES
  ('RED'),
  ('GREEN'),
  ('BLUE');
  
INSERT INTO CATEGORY(CODE) VALUES
  ('SHIRT'),
  ('PANT'),
  ('ACCESSORIES');
  
INSERT INTO SIZE(CODE) VALUES
  ('S'),
  ('M'),
  ('L'),
  ('XL'),
  ('XXL');
  
INSERT INTO PRODUCT(CODE, PRICE, SIZE, BRAND, COLOR, CATEGORY) VALUES
  ('STRIPED TSHIRT',700,1,1,1,1),
  ('BLUE WASHED JEANS',1500,2,2,2,2),
  ('SOCKS',200,3,3,3,3);
  
  
