DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SIZE;
  
CREATE TABLE BRAND (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(250) NOT NULL
);

CREATE TABLE CATEGORY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(250) NOT NULL
);

CREATE TABLE COLOR (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(250) NOT NULL
);


CREATE TABLE SIZE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(250) NOT NULL
);
  
CREATE TABLE PRODUCT(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(250) NOT NULL,
  PRICE INT NOT NULL,
  SIZE INT NOT NULL,
  foreign key (SIZE) references SIZE(ID),
  BRAND INT NOT NULL,
  foreign key (BRAND) references BRAND(ID),
  COLOR INT NOT NULL,
  foreign key (COLOR) references COLOR(ID),
  CATEGORY INT NOT NULL,
  foreign key (CATEGORY) references CATEGORY(ID)
);